### ISSUE TITLE
Wiki Feedback

### ISSUE THREAD

**Issue by edherm** [Nish-Arya/Unbroke#1]
# Wiki Feedback
After you have reviewed and addressed these changes, please respond to this issue and send Gordon and Ed a link. We will provide followup after reviewing your changes before closing this issue.

## MVP List
- [x] At what point are you implementing expenses (that populate the data for the pie-chart)?

## Schema
- [x] What restrictions will your columns have (which ones are unique, non-nullable, etc.)
### Goals
- [x] Will goals have a name/description?
- [x] I think `months_left` may work better as a date instead of an integer, then count-down logic could be calculated.
### Stocks
- [x] If multiple users have the same stock, you will be storing them twice. It may make sense to have a stocks table with the ticker and a second table `owned_stocks` that connects each user to the single record of the stock.

## Back End Routes
- [x] Where do a user's expenses/purchases/ etc. get stored/come from? Will they be automatically served up with the user after login?
- [x] I think a goal should have a patch route, not just a delete.

## Wireframes
- [x] Will the nav bar that you have on the goals and stocks wireframe be the same component that you have on the home wireframe, just with contextual styling to differentiate?

**Comment by Nish-Arya** [comment]
I think I uploaded an older version of my home wireframe. All of the pages are going to have the same nav bar component and footer. My apologies for the error.

**Comment by Nish-Arya** [comment]
## MVP List
- I have update the MVP list to add the implementation of the expenses to the home page component.

## Schema
- I have added unique constraints to Users.email and Expense_Categories.name. None of the columns in any tables are nullable.

## Goals
- I have added a description column to the Goals table.
- I have changed months_left to a date column and date format to be able to calculate countdown logic.

## Stocks
- I am planning to use an external API to make requests to get current quotes based on the ticker symbol. I meant for this table to be Stock_Holdings which I have changed it to. I also realized that I need to add a column to store the price the stock was bought at.

## Back End Routes
- Yes. The expenses will be pulled from the database upon login based on userId. Then they will go ahead and populate the pie chart based on what categories they belong to.
- I have added a patch route for completing a goal.

## Wireframes

- I accidentally uploaded an older version of the home wireframe. All the pages are supposed to have the same navbar and footer component. The pages will be served up as switch routes.
