### ISSUE TITLE
Heroku Deploy

### ISSUE THREAD

**Issue by edherm** [Nish-Arya/Unbroke#7]
# Expenses
- [x] I think you need some kind of divider between these three things (summary, expenses list, pie-chart). Take a look at other finance apps for some inspiration on what kind of borders/shading/etc. they use to separate elements.
- [x] Any numbers that are money should have a `$` so we know what they are. This includes income, expense, savings, expense amount, etc.

# Goals
## Post
- [x] I think the year field should have a default value, such as this year. The up/down increment works nicely, but it starts at 1, which makes it unhelpful to start.

## Goals Display
- [x] The `amount` and `savings per month` should be displayed in dollars.

**Comment by Nish-Arya** [comment]
I have fixed the above mentioned issues. Please let me know if you see anything else I could use changing. Thank you.
